import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import instance from "../utils/axiosInstance";
import { GetConfig } from "../utils/GetConfig";

function UploadAssignmentAssessment({
  assignmentId,
  filetypes,
  description,
  criteria,
}) {
  const [feedback, setFeedback] = useState("");
  const [file, setFile] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const { userId, token } = useAuth();
  const [submitModule, setSubmitModule] = useState(false);

  const criteriaString = JSON.stringify(criteria);

  function handleFileChange(e) {
    setFile(e.target.files[0]);
  }

  console.log("file:", file);

  async function uploadFile() {
    try {
      setSubmitModule(false);
      if (!file) {
        setError("Please upload a zip file.");
        return;
      }

      if (file.name.split(".").pop() !== "zip") {
        setError("Please upload a zip file.");
        return;
      }

      setError("");
      setLoading(true);

      console.log("Uploading file...");

      const formData = new FormData();
      // zipUpload - see multer config in zipRoutes.js
      formData.append("zipUpload", file);

      formData.append("allowedExtensions", JSON.stringify(filetypes));

      formData.append("criteriaString", criteriaString);

      formData.append("description", description);

      formData.append("assignment_id", assignmentId);

      formData.append("student_id", userId);

      const response = await instance.post(
        "api/ai/decompress",
        formData,
        GetConfig(token),
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );

      console.log("Server response:", response.data);
      setFile(null);
      setFeedback(response.data || "");
      setLoading(false);
    } catch (error) {
      console.error(error);
      setError(error.message);
      setLoading(false);
    }
  }

  return (
    <div className="flex flex-col">
      <ul className="text-red-900">
        {/* <li>Description: {description}</li> */}
      </ul>
      <h2 className="text-xl font-light">Upload Project Zip file</h2>
      <div className="flex flex-col w-4/5">
        <input
          className="p-2 w-[20%] text-white bg-black border border-gray-300 rounded hover:bg-gray-100 hover:cursor-pointer"
          type="file"
          name="zipUpload"
          onChange={handleFileChange}
        />
        {file && !loading && (
          <button
            disabled={loading}
            className="h-10 px-5 m-2 text-white transition-colors duration-150 bg-[#2b6cb0] rounded-lg focus:shadow-outline hover:bg-[#2c5282]"
            onClick={() => {
              // uploadFile();
              setSubmitModule(true);
            }}
          >
            Submit
          </button>
        )}
      </div>
      {submitModule && (
        <div className="fixed inset-0  flex items-center justify-center bg-[rgba(0,0,0,0.5)] p-4">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md p-6 mx-auto">
            <div className="mb-4">
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                Disclaimer
              </h2>
              <ul className="space-y-3 text-gray-700 pl-5 list-disc">
              <li className="pl-2">
                  <span className="font-medium text-red-600">
                    Grading:
                  </span>{" "}
                  Your most current submission will count as your final submission and graded by your lecturer after the due date. 
                  The AI feedback will be provided to the lecturer for review.         
                </li>
                <li className="pl-2">
                  <span className="font-medium text-yellow-600">
                    AI Feedback:
                  </span>{" "}
                  The feedback you receive is generated by Artificial
                  Intelligence which can be inaccurate. Please ask the student
                  assistants for help if you have any questions about the
                  feedback you received.
                </li>
                <li className="pl-2">
                  <span className="font-medium text-blue-600">
                    File Verification:
                  </span>{" "}
                  Please check that you have uploaded the correct zip folder.
                  The feedback you will get is based on the content of the zip
                  folder you uploaded.
                </li>
                <li className="pl-2">
                  <span className="font-medium text-purple-600">
                    Grade Note:
                  </span>{" "}
                  The suggested grade is only a suggestion. The final grade is
                  given by your lecturer.
                </li>
              </ul>
            </div>

            <div className="flex space-x-4 mt-6">
              <button
                className="flex-1 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50"
                onClick={uploadFile}
              >
                Submit Assignment
              </button>
              <button
                type="button"
                onClick={() => setSubmitModule(false)}
                className="flex-1 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors duration-300 ease-in-out transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {error && <p className="text-red-500">{error}</p>}
      {loading && <p>Processing...</p>}
      {feedback && (
        <div className="bg-white shadow-md border border-gray-300 rounded-lg p-6 mt-10">
          <h3 className="text-lg font-semibold text-gray-800 mb-2">
            Feedback comment:
          </h3>
          <p className="text-gray-600 mb-4">{feedback.general_comment}</p>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">
            Suggested Grade:
          </h3>
          {feedback.result_string === "pass" ? (
            <span className="inline-block bg-green-100 text-green-800 rounded-full px-3 py-1 text-sm font-medium">
              PASS
            </span>
          ) : (
            <span className="inline-block bg-red-100 text-red-800 rounded-full px-3 py-1 text-sm font-medium">
              FAIL
            </span>
          )}
        </div>
      )}
    </div>
  );
}

export default UploadAssignmentAssessment;
